/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2f09f967-493e-4117-8482-3e04489b1fda",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_ll414UFIB",
    "aws_user_pools_web_client_id": "765si3422hr2mc57m6lsd4plsi",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pyfkq2bggzazdarhcgvgqbofg4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
